LRQA-52673 Added new test for Minium flow
iovaneale/com-liferay-commerce pull request #10
Opened 2019-11-25 13:55 UTC by Lorenzo280800

https://issues.liferay.com/browse/LRQA-52673

2019-11-25 13:56 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2019-11-25 14:24 UTC, iovaneale commented
ci:test

2019-11-25 14:25 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-9.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/25/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-9.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/25/jenkins-report.html">here</a>.</b></p>

2019-11-25 14:34 UTC, iovaneale requested changes
Please change FrontStore.macro into CommerceStoreFront.macro

2019-11-25 14:45 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 17 minutes 3 seconds 861 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/aadc189412e470fb02505dd4f7f96c27ced41da4">aadc189412e470fb02505dd4f7f96c27ced41da4</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :x:<pre><code>     [echo] * What went wrong:
     [echo] Execution failed for task ':apps:commerce:headless:headless-commerce:headless-commerce-admin-catalog-api:baseline'.
     [echo] &gt; Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal-7.1.x/tools/sdk/dist/com.liferay.headless.commerce.admin.catalog.api-5.0.0.jar against /opt/dev/projects/github/liferay-portal-7.1.x/.gradle/caches/modules-2/files-2.1/com.liferay.commerce/com.liferay.headless.commerce.admin.catalog.api/4.0.0/aefb6c0dd45bf4d09775bfa70fdbfb7187fb9779/com.liferay.headless.commerce.admin.catalog.api-4.0.0.jar
     [echo] 
     [echo] * Try:
     [echo] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [echo] 
     [echo] * Exception is:
     [echo] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:commerce:headless:headless-commerce:headless-commerce-admin-catalog-api:baseline'.
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
     [echo] 	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
     [echo] 	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
     [echo] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
     [echo] 	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
     [echo] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
     [echo] 	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)</code></pre></li><li>central-requirements-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-13.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/102//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>7 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-13.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/102//testReport">here</a>.</h5></div></html>

2019-11-26 11:03 UTC, iovaneale commented
ci:test

2019-11-26 11:04 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/123/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-2.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/123/jenkins-report.html">here</a>.</b></p>

2019-11-26 11:30 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 24 minutes 10 seconds 835 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/5b86c10206c81d4fee3a4270b3ef98cd5b2e6357">5b86c10206c81d4fee3a4270b3ef98cd5b2e6357</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :x:<pre><code>     [exec] java.lang.Exception: Found 1 formatting issues:
     [exec] 1: ./commerce-product-test/src/testFunctional/macros/CommerceCheckout.macro expected:&lt;...(site = "${site}");
     [exec] []
     [exec] 		Navigator.openSpe...&gt; but was:&lt;...(site = "${site}");
     [exec] [		]
     [exec] 		Navigator.openSpe...&gt;
     [exec] 
     [exec] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:438)
     [exec] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:266)
     [exec] 
     [exec] &gt; Task :checkSourceFormatting FAILED
     [exec] 1 actionable task: 1 executed
     [exec] Gradle build finished at 2019-11-26 11:26:59.397.
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':checkSourceFormatting'.
     [exec] &gt; Process 'command '/opt/java/jdk1.8.0_121-x64/bin/java'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':checkSourceFormatting'.
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
     [exec] 	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
     [exec] 	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
     [exec] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
     [exec] 	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
     [exec] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)</code></pre></li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/130//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>18 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/130//testReport">here</a>.</h5></div></html>

2019-11-26 11:55 UTC, iovaneale commented
ci:test

2019-11-26 11:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/173/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-4.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/173/jenkins-report.html">here</a>.</b></p>

2019-11-26 12:30 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 31 minutes 45 seconds 474 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/5b86c10206c81d4fee3a4270b3ef98cd5b2e6357">5b86c10206c81d4fee3a4270b3ef98cd5b2e6357</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-13.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/105//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>18 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-13.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/105//testReport">here</a>.</h5></div></html>

2019-11-26 13:05 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:default - 2 out of 3 jobs passed in 1 hour 9 minutes 23 seconds 77 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/5b86c10206c81d4fee3a4270b3ef98cd5b2e6357">5b86c10206c81d4fee3a4270b3ef98cd5b2e6357</a></p><details><summary><strong>ci:test:default - 2 out of 3 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/173/"><strike><strong>test-subrepository-acceptance-pullrequest(7.1.x)</strong></strike></a></li></ul></div><details><summary><strong>2 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/88/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-13.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/105/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details></details><h5>For more details click <a href="https://test-1-4.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/173/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/173/">test-subrepository-acceptance-pullrequest(7.1.x)</a></h5><div><h6>Job Results:</h6><p>2 Jobs Passed.<br/>1 Job Failed.</p></div><div><p>POSHI Validation Failure<pre><code>     [exec] 4 errors in POSHI
     [exec] Exception in thread "main" java.lang.Exception
     [exec] 	at com.liferay.poshi.runner.PoshiRunnerValidation._throwExceptions(PoshiRunnerValidation.java:1799)
     [exec] 	at com.liferay.poshi.runner.PoshiRunnerValidation.validate(PoshiRunnerValidation.java:109)
     [exec] 	at com.liferay.poshi.runner.PoshiRunnerContext.main(PoshiRunnerContext.java:316)
     [exec] 
     [exec] 
     [exec] Invalid macro command CommerceConfiguration#commerceStoreFrontTearDown
     [exec] /opt/dev/projects/github/liferay-portal-7.1.x/modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceFrontStore.testcase:23
     [exec] 
     [exec] Invalid macro command CommerceConfiguration#commerceStoreFrontSetUp
     [exec] /opt/dev/projects/github/liferay-portal-7.1.x/modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceFrontStore.testcase:13
     [exec] 
     [exec] Invalid macro command FrontStore#addInitializerProductToCart
     [exec] /opt/dev/projects/github/liferay-portal-7.1.x/modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceInitializers.testcase:102
     [exec] 
     [exec] Invalid macro command CommerceConfiguration#commerceStoreFrontTearDown
     [exec] /opt/dev/projects/github/liferay-portal-7.1.x/modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceFrontStore.testcase:23
     [exec] 
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':writePoshiProperties'.
     [exec] &gt; Process 'command '/opt/java/jdk1.8.0_121-x64/bin/java'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':writePoshiProperties'.
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
     [exec] 	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
     [exec] 	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
     [exec] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
     [exec] &gt; Task :writePoshiProperties FAILED</code></pre></p></div></div></li></ol></details></html>

2019-11-26 15:25 UTC, Lorenzo280800 commented
ci:test

2019-11-26 15:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/140/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-7.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/140/jenkins-report.html">here</a>.</b></p>

2019-11-26 15:57 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 28 minutes 40 seconds 654 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/5b86c10206c81d4fee3a4270b3ef98cd5b2e6357">5b86c10206c81d4fee3a4270b3ef98cd5b2e6357</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/231//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>18 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/231//testReport">here</a>.</h5></div></html>

2019-11-26 17:00 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:default - 11 out of 13 jobs passed in 1 hour 34 minutes 26 seconds 903 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/5b86c10206c81d4fee3a4270b3ef98cd5b2e6357">5b86c10206c81d4fee3a4270b3ef98cd5b2e6357</a></p><details><summary><strong>ci:test:default - 11 out of 13 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/140/"><strike><strong>test-subrepository-acceptance-pullrequest(7.1.x)</strong></strike></a></li><li><a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/877/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</strong></strike></a></li></ul></div><details><summary><strong>11 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/646/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/267/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-9.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/268/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/297/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/899/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-10.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/298/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/647/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/4</a></li><li><a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/900/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-9.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/269/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</a></li><li><a href="https://test-1-13.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/48/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/231/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details></details><h5>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/140/jenkins-report.html">here</a>.</h5><hr/><h4>Failures (upstream comparison is not available):</h4><ol><li><div><h5><a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/877/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</a></h5><div><h6>Job Results:</h6><p>1 Test Passed.<br/>2 Tests Failed.</p></div><ol><li><div><a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/877//consoleText">AXIS_VARIABLE=0,label_exp=!master #877</a><ol><li><div><a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/877//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CommerceFrontStore_ViewStoreFrontSimpleProduct_">LocalFile.CommerceFrontStore#ViewStoreFrontSimpleProduct</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-7/1574782006422/test-subrepository-acceptance-pullrequest(7.1.x)/140/subrepository-functional-tomcat90-mysql57-jdk8/6/0/LocalFile.CommerceFrontStore_ViewStoreFrontSimpleProduct/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-7/1574782006422/test-subrepository-acceptance-pullrequest(7.1.x)/140/subrepository-functional-tomcat90-mysql57-jdk8/6/0/LocalFile.CommerceFrontStore_ViewStoreFrontSimpleProduct/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-7/1574782006422/test-subrepository-acceptance-pullrequest(7.1.x)/140/subrepository-functional-tomcat90-mysql57-jdk8/6/0/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/877//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CommerceInitializers_MiniumSiteFullFlow_">LocalFile.CommerceInitializers#MiniumSiteFullFlow</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-7/1574782006422/test-subrepository-acceptance-pullrequest(7.1.x)/140/subrepository-functional-tomcat90-mysql57-jdk8/6/0/LocalFile.CommerceInitializers_MiniumSiteFullFlow/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-7/1574782006422/test-subrepository-acceptance-pullrequest(7.1.x)/140/subrepository-functional-tomcat90-mysql57-jdk8/6/0/LocalFile.CommerceInitializers_MiniumSiteFullFlow/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-7/1574782006422/test-subrepository-acceptance-pullrequest(7.1.x)/140/subrepository-functional-tomcat90-mysql57-jdk8/6/0/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li></ol></details></html>

2019-11-27 11:47 UTC, closed without merging

2019-11-27 11:50 UTC, iovaneale commented on commerce-product-test/src/testFunctional/macros/FrontStore.macro
> +	macro addInitializerProductToCart {
Rename: addProductToCart

2019-11-27 11:50 UTC, iovaneale commented on commerce-product-test/src/testFunctional/paths/CommerceMinium.path
> +	<td>//div[@class='row']//..//span[contains(.,'${key_accountName}')]</td>
//div[@class='row']//span[contains(.,'${key_accountName}')]

2019-11-27 11:50 UTC, iovaneale commented on commerce-product-test/src/testFunctional/paths/CommerceMinium.path
> +	<td>//div/label[contains(.,'Address')]//..//input | //div/label[contains(.,'Street')]//..//input</td>
//div/label[contains(.,'Address') or contains(.,'Street')]//..//input

2019-11-27 11:50 UTC, iovaneale commented on commerce-product-test/src/testFunctional/paths/CommerceMinium.path
> +	<td>//div[contains(@class,'__actions')]/button</td>
//div[contains(@class,'actions')]/button

2019-11-27 11:50 UTC, iovaneale commented on commerce-product-test/src/testFunctional/paths/CommerceMinium.path
> +	<td>//div/div//span/span[text()='${key_userEmailAddress}']//..//..//..//button</td>
//span[text()='${key_userEmailAddress}']//following::button[1]

2019-11-27 11:50 UTC, iovaneale commented on commerce-product-test/src/testFunctional/paths/CommerceMinium.path
> +	<td>//div/label[contains(.,'Telephone')]//..//input | //div/label[contains(.,'Phone Number')]//..//input</td>
//label[contains(.,'Telephone') or contains(.,'Phone Number')]//..//input

2019-11-27 11:50 UTC, iovaneale commented on commerce-product-test/src/testFunctional/paths/CommerceMinium.path
> +	<td>//div/label[contains(.,'Zip Code')]//..//input | //div/label[contains(.,'Postal Code')]//..//input</td>
//label[contains(.,'Zip Code') or contains(.,'Postal Code')]//..//input

2019-11-27 11:50 UTC, iovaneale commented on commerce-product-test/src/testFunctional/paths/CommerceMinium.path
> +	<td>//div[@id='account-manager-curtain']/div/div[2]/div[3]/a</td>
//div[@id='account-manager-curtain']//a[contains(.,'View All Accounts')]

2019-11-27 11:50 UTC, iovaneale commented on commerce-product-test/src/testFunctional/paths/CommerceMinium.path
> +	<td>//div/p[contains(.,'${key_productSKU}')]/..//div//span[contains(.,'${key_productPrice}')]/../..//div[contains(@class,'add-to-cart-button')]</td>
//a[contains(.,'${key_productName}')]//..//div[contains(@class,'add-to-cart-button')]

2019-11-27 11:50 UTC, iovaneale commented on commerce-product-test/src/testFunctional/paths/CommerceMinium.path
> +	<td>CHECKOUT_DELIVERY_RADIO</td>
CHECKOUT_SHIPPING_OPTION_RADIO

2019-11-27 11:50 UTC, iovaneale commented on commerce-product-test/src/testFunctional/paths/CommerceMinium.path
> +	<td>//label[contains(.,'${key_radioOption}')]/input[@type='radio' and contains(@name,'${key_fieldName}')]</td>
//label[contains(.,'${key_radioOption}')]/input[@type='radio']

2019-11-27 11:50 UTC, iovaneale commented on commerce-product-test/src/testFunctional/paths/CommerceMinium.path
> +	<td>CHECKOUT_SHIPPING_ADDRESS_SELECT</td>
Useless. Use Select function.

2019-11-27 11:50 UTC, iovaneale commented on commerce-product-test/src/testFunctional/paths/CommerceMinium.path
> +	<td>//input[contains(@class,'commerce-quantity-selector__input')]</td>
//a[contains(.,'${key_productName}')]//..//div[(@class='commerce-quantity-selector')]//input

2019-11-27 11:50 UTC, iovaneale commented on commerce-product-test/src/testFunctional/paths/CommerceMinium.path
> +	<td>REVIEW_ORDER_ENTRY</td>
PENDING_ORDERS_ENTRY

2019-11-27 11:50 UTC, iovaneale commented on commerce-product-test/src/testFunctional/paths/CommerceMinium.path
> +	<td>//td[contains(., '${key_accountName}')]/../td[contains(.,'${key_orderAuthor}')]/../td/p/span</td>
//td[contains(.,'${key_orderAuthor}')]/../td/p/span

2019-11-27 11:50 UTC, iovaneale commented on commerce-product-test/src/testFunctional/paths/CommerceMinium.path
> +	<td>PENDING_ORDERS_INACTIVE_PRICE</td>
Delete

2019-11-27 11:50 UTC, iovaneale commented on commerce-product-test/src/testFunctional/paths/CommerceMinium.path
> +	<td>PENDING_ORDERS_PRICE</td>
PENDING_ORDER_DETAILS_PRICE

2019-11-27 11:50 UTC, iovaneale commented on commerce-product-test/src/testFunctional/paths/CommerceMinium.path
> +	<td>//table/tbody//td[3]//span[@class='price__value']</td>
//tbody//span[@class='price__value']

2019-11-27 11:50 UTC, iovaneale commented on commerce-product-test/src/testFunctional/paths/CommerceMinium.path
> +	<td>PENDING_ORDERS_PROMO_PRICE</td>
DELETE

2019-11-27 11:50 UTC, iovaneale commented on commerce-product-test/src/testFunctional/paths/CommerceMinium.path
> +	<td>PENDING_ORDERS_QUANTITY</td>
PENDING_ORDER_DETAILS_QUANTITY

2019-11-27 11:50 UTC, iovaneale commented on commerce-product-test/src/testFunctional/paths/CommerceMinium.path
> +	<td>//table/tbody//td[5]//span</td>
//tbody//td[5]//span

2019-11-27 11:50 UTC, iovaneale commented on commerce-product-test/src/testFunctional/paths/CommerceMinium.path
> +	<td>PENDING_ORDERS_SKU</td>
PENDING_ORDER_DETAILS_SKU

2019-11-27 11:50 UTC, iovaneale commented on commerce-product-test/src/testFunctional/paths/CommerceMinium.path
> +	<td>//table/tbody//td[1]//span[contains(@class,'__value')]</td>
//tbody//span[contains(@class,'cell__value')]

2019-11-27 11:50 UTC, iovaneale commented on commerce-product-test/src/testFunctional/paths/CommerceMinium.path
> +	<td>//div[@class='minium-sidebar']//..//a[@class='main-link' and contains (.,'${key_menuItem}')]</td>
//div[@class='minium-sidebar']//..//a[contains (.,'${key_menuItem}')]

2019-11-27 11:50 UTC, iovaneale commented on commerce-product-test/src/testFunctional/paths/CommerceEntry.path
> +	<td>ADMIN_ACCOUNT_ELLIPSIS</td>
Use Icon#ROW_VERTICAL_ELLIPSIS

2019-11-27 11:50 UTC, iovaneale commented on commerce-product-test/src/testFunctional/tests/CommerceInitializers.testcase
> +		Navigator.openSpecificURL(url = "http://localhost:8080/group/Minium");
Remove it